### ISSUE TITLE
Is pinning of old pytorch version necessary?

### ISSUE THREAD

**Issue by bluenote10** [gudgud96/torchcrepeV2#7]
Thanks for this project!

I'd be interested in using this library, but I noticed that it pins a rather old torch version

https://github.com/gudgud96/torchcrepeV2/blob/e214b378eab1bc8921a16f82848d84056aa2d319/setup.cfg#L16

In my project I'm using a new version (2.1.2), and due to the pinning, I won't be able to integrate it into the project.

I'm wondering if the pinning is actually needed, or if a broader / more modern version range could be supported. Note that in general for libraries it is not recommended to pin exact versions, but rather trying to support ranges more flexibly.

**Comment by gudgud96** [comment]
@bluenote10 Thanks for noticing, I don't need pinning is needed anymore. I have removed it and feel free to pull the latest master branch.

**Comment by bluenote10** [comment]
Great, thank you!
